# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 321-log archive
subtitle: ''
description: ''
keywords:
author: Bima
language: en
timezone: ''

## Config theme
aomori_logo: /images/avatar.jpg
aomori_logo_typed_animated: true
aomori_search_algolia: true
algolia:
  applicationID: 'KY4NYLOG0P'
  #apiKey: ''
  indexName: '321log'
aomori_menu:
  Home: /
  Archives: /archives
aomori_widgets:
    - toc # Article navigation
    - category  # Article classification
    - tag # Article tags
    - recent_posts  # latest articles
    - archive # Article Archive
aomori_copyright: true # or false
aomori_social:
  -
    icon: github
    type: logo
    url: https://github.com/bimsky
  -
    icon: rss
    type: regular
    url: https://321log.netlify.app/sitemap.xml
aomori_baidu_sitepush: false  # or false
aomori_baidu_analytics: ''
aomori_google_analytics: 'UA-XXXXX-X'
aomori_busuanzi: true



# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: http://321log.netlify.app
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-aomori

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
