---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: https://cloudinary.com/console/c-9f71bf2765ee6911dc2894483bae26/media_library/folders/682ec08464860ad823b99d7786014868
public_path: https://res.cloudinary.com/bimagv/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:, :month:, :day:,:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
